/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerspectivesSpecialistManagersRouteImport } from './routes/perspectives/specialist-managers'
import { Route as PerspectivesSodraVindbolagetRouteImport } from './routes/perspectives/sodra-vindbolaget'
import { Route as PerspectivesInstitutionalPlatformsRouteImport } from './routes/perspectives/institutional-platforms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerspectivesSpecialistManagersRoute =
  PerspectivesSpecialistManagersRouteImport.update({
    id: '/perspectives/specialist-managers',
    path: '/perspectives/specialist-managers',
    getParentRoute: () => rootRouteImport,
  } as any)
const PerspectivesSodraVindbolagetRoute =
  PerspectivesSodraVindbolagetRouteImport.update({
    id: '/perspectives/sodra-vindbolaget',
    path: '/perspectives/sodra-vindbolaget',
    getParentRoute: () => rootRouteImport,
  } as any)
const PerspectivesInstitutionalPlatformsRoute =
  PerspectivesInstitutionalPlatformsRouteImport.update({
    id: '/perspectives/institutional-platforms',
    path: '/perspectives/institutional-platforms',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perspectives/institutional-platforms': typeof PerspectivesInstitutionalPlatformsRoute
  '/perspectives/sodra-vindbolaget': typeof PerspectivesSodraVindbolagetRoute
  '/perspectives/specialist-managers': typeof PerspectivesSpecialistManagersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perspectives/institutional-platforms': typeof PerspectivesInstitutionalPlatformsRoute
  '/perspectives/sodra-vindbolaget': typeof PerspectivesSodraVindbolagetRoute
  '/perspectives/specialist-managers': typeof PerspectivesSpecialistManagersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/perspectives/institutional-platforms': typeof PerspectivesInstitutionalPlatformsRoute
  '/perspectives/sodra-vindbolaget': typeof PerspectivesSodraVindbolagetRoute
  '/perspectives/specialist-managers': typeof PerspectivesSpecialistManagersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/perspectives/institutional-platforms'
    | '/perspectives/sodra-vindbolaget'
    | '/perspectives/specialist-managers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/perspectives/institutional-platforms'
    | '/perspectives/sodra-vindbolaget'
    | '/perspectives/specialist-managers'
  id:
    | '__root__'
    | '/'
    | '/perspectives/institutional-platforms'
    | '/perspectives/sodra-vindbolaget'
    | '/perspectives/specialist-managers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerspectivesInstitutionalPlatformsRoute: typeof PerspectivesInstitutionalPlatformsRoute
  PerspectivesSodraVindbolagetRoute: typeof PerspectivesSodraVindbolagetRoute
  PerspectivesSpecialistManagersRoute: typeof PerspectivesSpecialistManagersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perspectives/specialist-managers': {
      id: '/perspectives/specialist-managers'
      path: '/perspectives/specialist-managers'
      fullPath: '/perspectives/specialist-managers'
      preLoaderRoute: typeof PerspectivesSpecialistManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perspectives/sodra-vindbolaget': {
      id: '/perspectives/sodra-vindbolaget'
      path: '/perspectives/sodra-vindbolaget'
      fullPath: '/perspectives/sodra-vindbolaget'
      preLoaderRoute: typeof PerspectivesSodraVindbolagetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perspectives/institutional-platforms': {
      id: '/perspectives/institutional-platforms'
      path: '/perspectives/institutional-platforms'
      fullPath: '/perspectives/institutional-platforms'
      preLoaderRoute: typeof PerspectivesInstitutionalPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerspectivesInstitutionalPlatformsRoute:
    PerspectivesInstitutionalPlatformsRoute,
  PerspectivesSodraVindbolagetRoute: PerspectivesSodraVindbolagetRoute,
  PerspectivesSpecialistManagersRoute: PerspectivesSpecialistManagersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
